language: node_js
node_js:
  - "node"
  - "lts/*"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
notifications:
  email:
    recipients:
      - mrals89@gmail.com
      - matthew.ralston@bms.com
    on_failure: always
    on_success: change
branches:
  except:
    - dev
after_success: npm run coverage
